app:
    debug: false
    service:
        # NOTE: Your service name
        name: WDFwd
        caption: WzDat Log / DB Forwarder
        # NOTE: Cron style schedule: m h dom mon dow
        schedule: "0 4 * * *"
        force_first_run: true
    rsync_path: # RSYNC-EXE-FILE-PATH
    # Limit rsync bandwidth in KB/Sec. 0 for no limit, skip for default
    rsync_bwlimit: 5120  # 5 MByte/Sec, Default

log:
    version: 1
    formatters:
        simpleFormatter:
            format: '%(asctime)s [%(levelname)s] - %(message)s'
            datefmt: '%Y/%m/%d %H:%M:%S'
    handlers:
        file:
            class: logging.handlers.RotatingFileHandler
            formatter: simpleFormatter
            level: DEBUG
            # NOTE: Log file shall be located within dump folder
            filename: # LOG-FILE-PATH ex) C:\wdfwd-temp\_wdfwd_log.txt
            maxBytes: 10485760
            backupCount: 10
    root:
        level: INFO
        handlers: [file]
    to_url: # RSYNC-SERVER-URL-FOR-LOG ex) rsync-user@myserver.net::rsync-backup/myprj
    fluent: # FLUENT-SERVER-IP-AND-PORT ex) ['localhost', 24224]


tailing:
    max_between_data: # skip between data larger than this size. default) 1000000
    file_encoding: # target file encoding  ex) cp949
    pos_dir: # TAIL-POS-FOLDER-PATH ex) C:\wdfwd-temp
    format: # regular expression for log line. 
            # 'dt_' and ('_json_' or '_text_')
            # ex) '(?P<dt_>\d+-\d+-\d+ \d+:\d+:\S+)\s(?P<level>\S+):\s(?P<_json_>.+)'
    order_ptrn: # explicit name pattern for file ordering
                # need only when ordering number not starts with '0'
                # 'date' and 'order' are mantatory fields
                # ex): (?P<date>[^\.]+)\.(?P<order>\d+)\.log'
    from:
        - file:
            dir: # LOG-FILE-FOLDER-TO-TAIL ex) C:\MyApp\tlog
            pattern: # LOG-FILE-PATTERN ex) log_*-*-*.log
            tag: # FLUENT-TAG  ex) wdfwd.myapp.tlog
        - file:
            dir: # LOG-FILE-FOLDER-TO-TAIL ex) C:\MyApp\tlog
            latest: # specific latest file
            pattern: # LOG-FILE-PATTERN ex) log2_*-*-*.log
            tag: # FLUENT-TAG  ex) wdfwd.myapp.tlog2
    to:
        fluent: # FLUENT-SERVER-IP-AND-PORT ex) ['localhost', 24224]


tasks:
    # Plain folder sync
    - sync_folder:
        folder: # TARGET-FOLDER-PATH ex) C:\MyApp\slog
        to_url: # RSYNC-SERVER-URL-FOR-LOG ex) rsync-user@myserver.net::rsync-backup/myprj/mysvr/log

    # (Recursive) file sync with filename pattern
    - sync_files:
        base_folder: # TARGET-FOLDER-PATH ex) C:\MyApp\\dump
        filename_pattern: # TARGET-FILE-PATTERN ex) "*.dmp"
        recurse: true
        # rsync server url
        to_url: # RSYNC-SERVER-URL-FOR-DUMP ex) rsync-user@myserver.net::rsync-backup/myprj/mysvr/dump
 
    # Dump DB to CSVs, then sync them
    - sync_db_dump:
        # NOTE: Dump folder where DB dumped .csv files are located.
        folder: # DUMP-TARGET-FOLDER-PATH ex) C:\wdfwd-temp
        field_delimiter: "\t"
        db:
            # NOTE: Local DB connection info
            connect:
                driver: "{SQL Server}"
                server: .\SQLEXPRESS
                port:
                database: C9
                trustcon: true
                read_uncommit: true
                uid:
                passwd:
            fetchsize: 1000
            table:
                # NOTE: Table names to be dumped.
                names:
                    - BIP.TblItemCreateDeleteRecord_
                    - BIP.TblItemEnfcStat_
                    - LogOpr.TblHackLogOpr_
                    - LogOpr.TblLogOpr_
                    - LogOpr.TblMissionPlayLogOpr_
                # for daily tables
                date_pattern: ".*_(\\d{8})"
                date_format: "%Y%m%d"
                # for non-daily tables only
                #   date_column: 'LogTime'
                skip_last: false
            sys_schema: false
            type_encodings:
                # specify encoding for a db type when conversion needed
                # ex) - {type: 'varchar', encoding: 'cp949'}
                # ex) - {type: 'varchar', func: 'lambda x: x.encode('utf8')}
        # rsync server url
        to_url: # RSYNC-SERVER-URL-FOR-DBLOG ex) rsync-user@myserver.net::rsync-backup/myprj/mysvr/dblog
